#Directories which are being used 
SRC_DIR = src
BIN_DIR = bin

SOURCES = $(SRC_DIR)/assg.c $(SRC_DIR)/vector.c $(SRC_DIR)/spheres.c // target and dependencies 
OBJECTS = $(SOURCES:.c=.o)

//default target using preprocessor macro MS1
all: $(MS1_EXEC)

